### ISSUE TITLE
Unable to load DLL 'Microsoft.Azure.Documents.ServiceInterop.dll' when calling library from service fabric service

### ISSUE THREAD

**Issue by LastTribunal** [Azure/azure-cosmosdb-dotnet#460]
https://github.com/Azure/azure-documentdb-dotnet/issues/262

issue persists, why was it closed?

Looks like there are a lot of half-assers working for MS these days.  Thanks to multiculturalism.  In some cultures its acceptable to release code that breaks, and also buildings and bridges

**Comment by kirankumarkolli** [comment]
Original issues was reported as addressed, it might be a new issue. 
@ausfeldt please look into this.

**Comment by LastTribunal** [comment]
It was never addressed.  Users said they had to use an older version of DocDb..  That is not called "addressed"  that is called a workaround

**Comment by ausfeldt** [comment]
@LastTribunal  What version of the SDK are you using?

**Comment by LastTribunal** [comment]
everything latest
all you gotta do is create a SF service and load and reference the latest docdb nuget.  you will see for your self
this is not a user error

**Comment by ausfeldt** [comment]
Which SDK, Microsoft.Azure.DocumentDB.Core or Microsoft.Azure.DocumentDB?

**Comment by LastTribunal** [comment]
Microsoft.Azure.DocumentDB

**Comment by ausfeldt** [comment]
@LastTribunal Microsoft.Azure.Documents.ServiceInterop.dll is a native DLL and possibly not being copied into the service package. Can you try the following: https://stackoverflow.com/questions/37408686/how-to-import-native-dll-on-service-fabric

**Comment by LastTribunal** [comment]
I have 100+MS nuget packages that run just fine with SF.  
There should be no special effort to make this work on SF.  If you don't wanna fix it, I will stay with docdb 1.16.0 for ever if I have to.

**Comment by ausfeldt** [comment]
@LastTribunal In the Nuget Package it has .targets file and its contents get added to your .csproj file to make sure the native DLLs are copied into your bin directory. 

```xml
<ItemGroup>
      <ContentWithTargetPath Include="$(MSBuildThisFileDirectory)..\runtimes\win7-x64\native\Microsoft.Azure.Documents.ServiceInterop.dll">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        <TargetPath>Microsoft.Azure.Documents.ServiceInterop.dll</TargetPath>
        <Visible>False</Visible>
      </ContentWithTargetPath>      
      <ContentWithTargetPath Include="$(MSBuildThisFileDirectory)..\runtimes\win7-x64\native\DocumentDB.Spatial.Sql.dll">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        <TargetPath>DocumentDB.Spatial.Sql.dll</TargetPath>
        <Visible>False</Visible>
      </ContentWithTargetPath>
</ItemGroup>
```
When creating the package it is not bringing the native DLLs over from your bin directory. It seems that Service Fabric's Package command is not doing an xcopy of the bin or not getting from the <ContentWithTargetPath> in your .csproj. It is probably reflecting over the assembly to determine dependencies, which it will not find, because the SDK code is managed code which calls a native DLL using PInvoke. If you add the following to your .csproj it should fix it.

```xml
<Target Name="AfterPackage" AfterTargets="Package">
    <Copy SourceFiles="ApplicationPackageRoot\native.dll" DestinationFolder="$(PackageLocation)\MyServicePackage\MyCode"/>
</Target>
```

I am not sure why 1.16.0 works, the .targets file in the NugetPackage is the same, so far I can't see any differences.

**Comment by LastTribunal** [comment]
looks like the latest docdb nuget solves the prob
