### ISSUE TITLE
Azure Portal Cosmos DB Data Explorer throwing resource not found error

### ISSUE THREAD

**Issue by declanmc** [Azure/azure-cosmosdb-dotnet#628]
**Describe the bug**
The comos db data explorer in the Azure portal returns a "resource not found error" when trying to update/delete a record it has returned from a collection. It also throws the error intermittently when clicking on a record to view it

**To Reproduce**
Attempt to open/update/delete any of the records returned after clicking the "documents" link under a collection in the data explorer

**Expected behavior**
Document opens/updates/is deleted successfully

**Actual behavior**
"Resource not found" dialog box displayed

Errors thrown in the console as follows

Failed to read document 69db02ca-d14c-ed04-72df-2036be6c48b9: {"code":404,"body":"{\"code\":\"NotFound\",\"message\":\"Message: {\\\"Errors\\\":[\\\"Resource Not Found\\\"]}

Failed to update document 69db02ca-d14c-ed04-72df-2036be6c48b9: {"code":404,"body":"{\"code\":\"NotFound\",\"message\":\"Message: {\\\"Errors\\\":[\\\"Resource Not Found\\\"]}

**Comment by ealsur** [comment]
@declanmc This repo is for the Cosmos DB .NET SDK.
But the behavior you describe means that the documents are being deleted in the collection inbetween they are listed in the panel.

Either your collection has TTL set and it's expiring the documents or your documents have a "ttl" property setting expiry, or some process / app is deleting them.

The Azure Portal queries for the documents for the list and if they appear there it's because they existed at that time, when you click on one, it does the read request for that particular document. If the document was deleted, then receiving a 404 is correct.

If you have more questions please send your account information to askcosmosdb{at}microsoft.com.
